<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>example</groupId>
    <artifactId>domino-consumers</artifactId>
    <version>1.0</version>
  </parent>
  <artifactId>consumer-teavm</artifactId>
  <dependencies>
    <dependency>
      <groupId>io.instanto</groupId>
      <artifactId>domino-widgets-teavm</artifactId>
    </dependency>
    <dependency>
      <groupId>io.instanto</groupId>
      <artifactId>domino-widgets-assets</artifactId>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-classlib</artifactId>
      <version>0.15.0</version>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-extras-slf4j</artifactId>
      <version>0.15.0</version>
    </dependency>
  </dependencies>
  <build>
    <resources>
      <resource>
        <directory>src/main/java</directory>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.teavm</groupId>
        <artifactId>teavm-maven-plugin</artifactId>
        <version>0.15.0</version>
        <executions>
          <execution>
            <phase>prepare-package</phase>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <mainClass>example.client.Launcher</mainClass>
          <targetDirectory>${project.build.directory}/site</targetDirectory>
          <targetFileName>app.js</targetFileName>
          <optimizationLevel>ADVANCED</optimizationLevel>
          <minifying>true</minifying>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.teavm</groupId>
            <artifactId>teavm-extras-slf4j</artifactId>
            <version>0.15.0</version>
          </dependency>
        </dependencies>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.3.1</version>
        <executions>
          <execution>
            <id>consumer-site</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/site</outputDirectory>
              <resources>
                <resource>
                  <directory>src/site</directory>
                  <filtering>false</filtering>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
